version: '3.9'

services: 
  usercacheservice:
    image: ${DOCKER_REGISTRY-}usercacheservice
    build:
      context: ..
      dockerfile: usercacheservice/Dockerfile
      
  usercacheservicedb:
    image: mysql:8.0
      
volumes: 
  mysql_data: